# Site settings
title: Justin Slack
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Justin Slack.
tagline: testing
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://justinslack.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
permalink: :title/
highlighter: rouge
# Gems
# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed
excerpt_separator: "<!--more-->"

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about/index.html

exclude: [
    'node_modules',
    'bower_components',
    'Gruntfile.js',
    'package.json',
    'bower.json',
    'requirements.txt',
    'Gemfile',
    'Gemfile.lock',
    'README.md',
    'sass',
    'js',
    'coffee',
    'env',
    'tmp'
]
